server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  application:
    name: provider
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
