server:
  port: 8002

spring:
  application:
    name: consumer
  main: #允许多个feign调用相同的服务接口
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
